[package]
name = "adventofcode-2020"
version = "0.1.0"
authors = ["Joel Setterberg <j.settrbrg@gmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "adventofcode-2020"
path = "src/main.rs"

[dev-dependencies]
criterion = "0.3.2"

[[bench]]
name = "my_benchmark"
harness = false
